### PR TITLE
enable creating bundle for fusion

### PR DESCRIPTION
**Pull request by umangachapagain**
This enables generating fusion bundles for the project. Generated fusion bundles should not be commited to git. To generate fusion bundle, run `IMAGE_NAME=idr HUB_NAME=odr-hub-operator DRCLUSTER_NAME=odr-cluster-operator make bundle`

### CODE REVIEW

**Comment by ShyamsundarR** [comment]
@umangachapagain This is fine. I do not understand the part about the changes should NOT be committed to git? Should this be merged into main and backported to 4.12 or not?

**Comment by umangachapagain** [comment]
> @umangachapagain This is fine. I do not understand the part about the changes should NOT be committed to git? Should this be merged into main and backported to 4.12 or not?

@ShyamsundarR Fixed the comment. What I meant was, we should not commit the generated bundle (which we are used to doing in other operator projects).

We need to merge this and backport to 4.12.

**Review by raghavendra-talur — APPROVED** [review]

**Comment by raghavendra-talur** [comment]
@umangachapagain The changes look good. I suggest that you post the generated csv here as a comment as a reference of what it should look like.

In case the resource files change in the future, it would be easy to refer and make the changes accordingly.

**Pull request merged**
