### PR TITLE
Copied odf manifest from release to main branch

### PR DESCRIPTION
**Pull request by nik-redhat**
Copied the odr manifest to main branch, to use in the nightly
CI builds on main branch.

Signed-off-by: nik-redhat <nladha@redhat.com>

### CODE REVIEW

**Comment by nik-redhat** [comment]
I am not sure, if it would cause any issues in the code. But, if not then requesting to please merge this PR so that we can continue with the nightly CI runs.

**Comment by ShyamsundarR** [comment]
Our main branch here is a reflection of upstream main and not for ODF builds as such. Makes it easier to rebase from upstream and keep ODF changes separate.

Nightly CI builds would be using the appropriate release branch as needed. If a release-4.12 branch is required we can create one.

**Comment by nik-redhat** [comment]
Ok. In that case, we would like to propose to have a branch named `release-4.99` created under this repo. This branch will be a copy of `main` branch, but with few modifications (such as the one in this PR) that would allow us the run the latest release of ODF using this branch on a nightly basis.

We will have a job that would sync this branch on a nightly basis with the `main` branch, so that we are able to test the latest changes on the main along with any specific changes required for the release branch.

**Comment by nik-redhat** [comment]
@ShyamsundarR any updates regarding the above request?

**Comment by ShyamsundarR** [comment]
> Ok. In that case, we would like to propose to have a branch named `release-4.99` created under this repo. This branch will be a copy of `main` branch, but with few modifications (such as the one in this PR) that would allow us the run the latest release of ODF using this branch on a nightly basis.
> 
> We will have a job that would sync this branch on a nightly basis with the `main` branch, so that we are able to test the latest changes on the main along with any specific changes required for the release branch.

Still thinking...

I would like to hit fetch upstream and merge upstream main to downstream main, and really not maintain another branch (e.g 4.99). The additions may not work towards the same. Have to go through what is minimally required and then add it to downstream main.

**Comment by nik-redhat** [comment]
In that case, what's the issue in keeping the ODF related changes in the `main` branch of this repo?
This repo is dedicated for ODF, and we won't be disturbing the u/s `ramen`, so shouln't we have those changes in the main branch here as well?

**Comment by ShyamsundarR** [comment]
Fixed by https://github.com/red-hat-storage/ramen/pull/53

Requires additional files and also GH actions change to publish DS images to its own quay repository. Which is added to the PR above.

If this results in a rebase conflict with upstream main too often, we WILL have to change the strategy.

**Pull request closed without merging**
