### PR TITLE
Add disconnected mode support for DR operators

### PR DESCRIPTION
**Pull request by ShyamsundarR**
By adding the required annotation as in the commit.

Signed-off-by: Shyamsundar Ranganathan <srangana@redhat.com>

### CODE REVIEW

**Comment by ShyamsundarR** [comment]
The downstrem builds adds the required ['relatedImages'](https://gitlab.cee.redhat.com/ceph/rhodf/-/blob/rhodf-4.12-rhel-8/distgit/containers/odr-hub-operator-bundle/render_templates.in#L103) to the CSV, hence that is currently taken care of.

What is not clear is if volsync as build and published by ACM contains the required annotation as well. As Ramen auto installs volsync on the managed clusters. Need to ensure the same for completion.

@raghavendra-talur @umangachapagain PTAL

**Comment by umangachapagain** [comment]
> The downstrem builds adds the required ['relatedImages'](https://gitlab.cee.redhat.com/ceph/rhodf/-/blob/rhodf-4.12-rhel-8/distgit/containers/odr-hub-operator-bundle/render_templates.in#L103) to the CSV, hence that is currently taken care of.
> 
> What is not clear is if volsync as build and published by ACM contains the required annotation as well. As Ramen auto installs volsync on the managed clusters. Need to ensure the same for completion.
> 
> @raghavendra-talur @umangachapagain PTAL

If volsync is auto installed, we need to make sure RelatedImages points to the right volsync image in builds. If you can point me to where/how this happens I can take a look and suggest a fix.

**Comment by umangachapagain** [comment]
Screenshot from 2023-02-07 20-27-59

VolSync already supports disconnected mode.
Also, Ramen doesn't directly reference VolSync image, instead it uses ACM addon resource to deploy it. So, nothing else needs to be done for volsync.

**Review by raghavendra-talur — APPROVED** [review]

**Pull request merged**
